### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by joshfraser**
Enjoy!

### CODE REVIEW

**Comment by jordajm** [comment]
@vikaskyadav - this is an auto-generated PR from our Crowdin integration. It is updated every time a translator completes work, but the translations aren't necessarily compete.

**Comment by jordajm** [comment]
@micahalcorn this is cleaned up and ready to merge (again). 
It now contains all of the machine translations thanks to @coleman415 
Is it too late to get this in the release? 
CC: @wanderingstan

**Comment by micahalcorn** [comment]
@jordajm never too late - well, hopefully, eventually 🤷‍♂️

**Comment by jordajm** [comment]
thanks @micahalcorn !

**Pull request merged**
