### PR TITLE
Another pagination fix

### PR DESCRIPTION
**Pull request by sparrowDom**
### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything

### Description:
Correct the total number of listings to include featured listings

### CODE REVIEW

**Comment by sparrowDom** [comment]
Another pagination fix 🤦‍♂️

**Comment by micahalcorn** [comment]
@sparrowDom I removed that because it was double-counting the featured listings. 🙃 More importantly, pagination is completely broken right now otherwise. I'm going to dig in and commit to this branch.

**Comment by sparrowDom** [comment]
@micahalcorn it could be that double count was the problem in a previous revision, but right now it shows the number of listings subtracted by the number of featured listings. Because those are filtered out a few lines above...

Just curious, what is the case where pagination is broken?

**Comment by micahalcorn** [comment]
I think you're correct.

A lot of listings are just missing entirely. After the first page, only a couple are shown. 😳

**Comment by sparrowDom** [comment]
Interestingly pagination works fine for me from `micah/pagination` branch but not from `master`

**Comment by micahalcorn** [comment]
I don't have that branch anymore. What environment/network are you testing with?

**Comment by sparrowDom** [comment]
Aha I see it was a bad merge. This line: https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/listings-grid.js#L61
```
Math.max(0, startSlicePosition + LISTINGS_PER_PAGE - featuredListings.length)
```

should be
```
Math.max(0, startSlicePosition + LISTINGS_PER_PAGE - shownFeaturedListings.length)
```

**Comment by sparrowDom** [comment]
Have to go AFK right now. I can handle this in the evening if you want

**Comment by sparrowDom** [comment]
I still had the branch locally, and was testing it on Rinkeby

**Comment by micahalcorn** [comment]
@sparrowDom thanks for catching the bad merge. I've got an opinionated fix that I'll commit here for collective review.

**Comment by micahalcorn** [comment]
@sparrowDom I've committed my changes and tested this with Mainnet data, the published Origin.js, and the production discovery server.

**Comment by sparrowDom** [comment]
@micahalcorn nice that you have handled the case with sorting the featured listings at the top of each search page.

**Pull request merged**
