### PR TITLE
Sparrow dom/calendar prototype fixes

### PR DESCRIPTION
**Pull request by sparrowDom**
### Description:
- resolve some minor bugs
- modify listing reservation to use Redux like in other parts of application

### Dependant Pull Request: 
- https://github.com/OriginProtocol/origin-js/pull/303 [add confirmation callback to origin-js request listing]

Solves issue: https://github.com/OriginProtocol/origin-dapp/issues/341

### CODE REVIEW

**Comment by sparrowDom** [comment]
@micahalcorn I think I wrapped my head around Redux. Could you please throw your eye on this PR and see if I got it right. 

From what I understand this is also one of the transactions we want to have present in the `TransactionsDropdown` component in a same manner as it is implemented elsewhere in the codebase.

**Comment by sparrowDom** [comment]
@jordajm this PR should resolve the problems when trying to reserve a `housing` or `services` listing. I didn't find any branches on `origin-js` for the calendar prototype so I opened a separate Pull Request (link above in the description), which this branch depends on. 

One thing I noticed (that perhaps caused some of the contract errors) is that the same user that created a listing can also try to reserve it. And in the final step when `reserve` button is clicked the contract throws an error.

**Comment by micahalcorn** [comment]
@sparrowDom great, thanks 👍 @jordajm do you want to confirm that this works as expected? It all looks good to me but I haven't run it against your stuff.

**Comment by sparrowDom** [comment]
:+1:
@jordajm I will let you merge this PR so it doesn't impede your work on the other branch.

**Pull request merged**
