### PR TITLE
Fix wrong reference to intlMessages attribute

### PR DESCRIPTION
**Pull request by tomlinton**
### Checklist:

- [x] Test your work and double check you didn't break anything
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

Fix broken reference which caused email attestation to break (blank screen and console errors) after a correct verification code is submitted.

### CODE REVIEW

**Comment by micahalcorn** [comment]
Thanks @tomlinton 😄 I swear that I fixed this somewhere else but it must not have been merged yet.

**Comment by tomlinton** [comment]
No worries @micahalcorn, sorry I didn't really look around to see if it had already been fixed in other branches or pull requests.

**Comment by micahalcorn** [comment]
@tomlinton no, thank you - too many branches, not enough merges 🙃

**Comment by micahalcorn** [comment]
@tomlinton I'm not crazy. It was in [The Release that Never Was](https://github.com/OriginProtocol/origin-dapp/commit/fac1eded775888d278661c56307acb335234e56d). 😄

**Pull request merged**
