### PR TITLE
Issue #248 - replace <timelapse> component with locale-aware moment.js

### PR DESCRIPTION
**Pull request by jordajm**
### Checklist:
- [x] Test your work and double check you didn't break anything

### Description:
- Instead of a roll-your-own `<Timelapse>` component, we can simply set the locale in `moment.js` and rely on their handy [`timeFromNow`](https://momentjs.com/docs/#/displaying/fromnow/) method to display how long ago an event occurred. 

(For screen shots, ignore the hard-coded notification messages and just look at the beautiful "how long ago" text)

#### English:
screenshot 2018-06-16 00 50 36

#### Chinese:
screenshot 2018-06-16 00 51 30

### CODE REVIEW

**Comment by micahalcorn** [comment]
How did I not know about this method? 🙉 Can we still abstract away the reactivity (updating the count) with appropriate intervals instead of arbitrarily choosing 30 seconds? I think that these are still subject to possible memory leaks if the components get unmounted.

**Comment by jordajm** [comment]
Glad you mentioned the memory leaks - I thought about that as I was falling asleep last night but had forgotten again by this morning 😬 I'll fix those later today.

Since the interval can be set in each component, is that configurable enough or do you have an idea for another way to do it?

**Comment by micahalcorn** [comment]
In the prior, homegrown, experiment, the component accepted a prop for reactivity (`true`|`false`). If `true`, it would adjust the interval over time based on the amount of time that had lapsed, i.e., no need to update every 30 seconds if it's been a year since the review was left.

This isn't really critical, I'm just a fan of reactivity, and not relying future-me to set the right interval when calling `timeFromNow`.

**Comment by jordajm** [comment]
@micahalcorn per our discussion today, this now only has a `setInterval` on the profile page b/c the other places didn't seem like they'd need them. 
The transactions dropdown menu will probably need them but I think it'll be a lot easier once they're wired up to real data b/c the loop makes it tricky the way it is now.

**Pull request merged**
