### PR TITLE
Arbitration & Transaction Fixes

### PR DESCRIPTION
**Pull request by micahalcorn**
This adds the shared conversation to the arbitration component and makes some other repairs.

### CODE REVIEW

**Comment by wanderingstan** [comment]
I'm getting the dreaded `{code: -32603, message: "Internal JSON-RPC error."}` when I try to accept an offer. (On candy maple, accepting as seller as account 2, after offer made by account 1)

Will keep trying...

**Comment by micahalcorn** [comment]
@wanderingstan on sample listings? You can't accept them since we added token to the equation. Franck is working on it now.

**Comment by wanderingstan** [comment]
I'm unable to get messaging working locally. Is that supposed to work?

**Comment by micahalcorn** [comment]
@wanderingstan plz try again 🙏

**Pull request merged**
