### PR TITLE
Limit to only one supported network, configurable

### PR DESCRIPTION
**Pull request by wanderingstan**
Default to mainnet. Remove hardcoded reference to Rinkeby.
Updates to dapp-info.

EDIT: Fix for: https://github.com/OriginProtocol/origin-dapp/issues/583

First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Checklist:

- [X] Test your work and double-check to confirm that you didn't break anything
- [X] Wrap any new text/strings for translation
- [ ] Map any new environment variables with a default value in the Webpack config

_Defaults to mainnet. ENV var only needed on production, and only when it's not mainnet._

### CODE REVIEW

**Comment by wanderingstan** [comment]
@franckc will do! I don't think we need it for dev, because it won't be a production environment (`process.env.NODE_ENV` will not be `production`) so the network check is skipped.

**Comment by franckc** [comment]
@wanderingstan Yes, dev is the continuous integration environment running in Google Cloud (we are not using it yet but we planned to after V1 is released). I know it is a big confusing...

**Comment by franckc** [comment]
Ah also, do you mind taking a look at those conflicts ? I think due to Micah's big reformatting :)

**Comment by wanderingstan** [comment]
Not a fan of the formatting ... asking if we can revert it simple one-line-per-table-row

**Comment by micahalcorn** [comment]
I resolved the conflict, at least. 😬

**Pull request merged**
