### PR TITLE
fetch contract health from origin-js

### PR DESCRIPTION
**Pull request by sparrowDom**
### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] Wrap any new text/strings for translation
- [ ] Map any new environment variables with a default value in the Webpack config
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

Use the origin-js marketplace contracts found functinoality

Dependant Pull Request: https://github.com/OriginProtocol/origin-js/pull/362

### CODE REVIEW

**Comment by franckc** [comment]
Can you pull latest master branch code ?
Looks like this was fixed already: https://github.com/OriginProtocol/origin-dapp/blob/master/src/actions/Listing.js

**Comment by micahalcorn** [comment]
@franckc are you seeing something different than we are? https://github.com/OriginProtocol/origin-dapp/blob/master/src/actions/Listing.js#L21 There is no longer a concept of a `listingsRegistryContract` in -js.

**Comment by franckc** [comment]
Sorry I should have been more clear. Yes, those lines got deleted so think PR is no needed.

**Comment by franckc** [comment]
I'm clearly not trustworthy! Forget all my previous comments on this PR...

Let's merge this in to fix the issue with the DApp not being able to load listings.

Still questionable if we need to check contracts are present in getListingIds but that can be addressed later. Let's fix the DApp asap.

**Comment by micahalcorn** [comment]
@sparrowDom I've made some changes. Let me know if they are acceptable to you. 🙏

**Comment by sparrowDom** [comment]
thanks @micahalcorn a nice improvement to error handling 👍

**Pull request merged**
