### PR TITLE
Issue #228 : Price approximation failure

### PR DESCRIPTION
**Pull request by inkredabull**
### Checklist:

- [x] No Tests
- [x] No README change

### Description:

 - adding 30 min caching for call to Cryptonator API to prevent likely rate-limiting

## Ref
* https://github.com/OriginProtocol/demo-dapp/issues/228

### CODE REVIEW

**Comment by wanderingstan** [comment]
This looks great to me just checking the code. I can run it tomorrow.

**Comment by wanderingstan** [comment]
Nice work @inkredabull ! Tested and it looks great. 

You should join us on our weekly engineering call sometime. We just finished the one for this week. Wednesdays at 1PM Pacific. Hangout link: https://meet.google.com/pws-cgyd-tqp

More info: https://originprotocol-com-micah.herokuapp.com/en/developers

**Comment by inkredabull** [comment]
ty @wanderingstan - Heroku link 404s but duly noted about ENGR mtg.

**Comment by wanderingstan** [comment]
@micahalcorn I'm good to merge, but will hold off as you figure out our release branching strategy. :)

**Pull request merged**
