### PR TITLE
Create QA_ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by mek32390**
### Checklist:

- [X] Test your work and double check you didn't break anything
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

Please explain the changes you made here:

Here is a draft of the QA Issue Template that @davecraige and I worked on. When it's been approved, it can be copy/pasted into a new Issue by following these instructions: https://help.github.com/articles/creating-issue-templates-for-your-repository/

### CODE REVIEW

**Comment by mek32390** [comment]
Link to see formatting: https://gist.github.com/mek32390/a373c0dafe8ca908142d73ebfe5ff120

**Comment by mek32390** [comment]
### TEST ISSUE:

Case ID: TC-MESS-2

## QA/Testing Issue Instructions 
When a Test Case from our [Origin DApp Testing & QA Spreadsheet](https://goo.gl/251wLY) fails or does not produce the expected result, use this Issue Template so we can **can fix it as quickly as possible**.

Before you do anything, please obtain the unique **Test Case ID** of the test case that failed from the [Origin DApp Testing & QA Spreadsheet](https://goo.gl/251wLY). The **Test Case ID** is in the yellow column, and has a format similar to:

> TC-ATT-1

### Instructions
_Please check each box_
- [x] Check that an issue does not already exist by searching for any issues with the "Test Case ID". 
- [x] Include the **Test Case ID** in the title of this issue in addition to giving it a more descriptive name.
- [x] Include any detail that can help our team reproduce/troubleshoot this test case is helpful: screenshot, short video, and any messages that show up in the browser console. More detail is always appreciated.
- [x] After submitting this issue to us, please paste the URL of it into the corresponding column of the Test Case this is about on the [Origin DApp Testing & QA Spreadsheet](https://goo.gl/251wLY).

### Description of problem
When resizing the chrome browser window to a small screen size, the users that I have conversations with are moved from the left pane to the top, underneath the navbar. It prohibits me from seeing and navigating through all my messages:





### Device Used:
13 in 2017 Macbook Pro

### Operating System and Version used:
MacOS High Sierra Version 10.13.6

### Web Browser and version and extentions used:
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit) with MetaMask Version
4.9.3 

If you need help or have any questions, please ask in our **#qa-testing** channel in [our Discord](https://OriginProtocol.com/discord ). Thank you.

**Comment by franckc** [comment]
Quick question: I'm not super familiar with Github but afaict we can only have a single template for issue. So are you suggesting this new template would be the default for any issue reported on the DApp and would replace the existing template at https://github.com/OriginProtocol/origin-dapp/blob/master/.github/ISSUE_TEMPLATE.md ?

**Comment by mek32390** [comment]
@franckc I don't believe there's a limit on the number of issue templates we can create. For instance, this issue template could be used for QA/Testing Issues, and there could be others for bugs, features, etc. Could even do a "Welcome to Origin" where we have newcomers introduce themselves, ha! 

Also, if we add a "name" and "about" to any issue template, like this: 
`---
name: Bug report
about: Create a report to help us improve
---`

It will load the issue directly into the Github UI. Contributors can then choose the correct type of issue directly from the UI. Here's a similar setup I have on a test repo that shows how this could look: 
image

**Comment by franckc** [comment]
@mek32390 Thanks for explaining ! This looks good to me. @wanderingstan or @micahalcorn any thoughts/comments before I merge this in ?

**Comment by franckc** [comment]
Merging this in... let's try to use it.

**Pull request merged**
