### PR TITLE
Render new lines in descriptions

### PR DESCRIPTION
**Pull request by wanderingstan**
per request from @joshfraser, following code from here:
https://medium.com/@kevinsimper/react-newline-to-break-nl2br-a1c240ba746

Newlines get converted to <br> tags, nothing more. 

We might consider supporting full-on markdown (eg [via this package](https://www.npmjs.com/package/react-markdown)) , but we'd want to disable images, and have a bigger discussion of whether markdown is the officially recommended format for Origin listings.

### CODE REVIEW

**Comment by wanderingstan** [comment]
Oh nice. Safer to do it in css.  Which do setting do we use, `pre-line` ?

**Comment by micahalcorn** [comment]
Here are the options 👇

white-space

**Comment by micahalcorn** [comment]
@wanderingstan you want to confirm your approval of this now? Or let me know if you prefer more white space. ⬜️

**Comment by wanderingstan** [comment]
LGTM!

**Pull request merged**
